// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fib-entry-proto.proto

package net.named_data.jndn.tests;

public final class FibEntryProto {
  private FibEntryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FibEntryMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;
    /**
     * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
     *
     * <pre>
     * A FibEntryMessage has one FibEntry.
     * </pre>
     */
    boolean hasFibEntry();
    /**
     * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
     *
     * <pre>
     * A FibEntryMessage has one FibEntry.
     * </pre>
     */
    FibEntryMessage.FibEntry getFibEntry();
    /**
     * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
     *
     * <pre>
     * A FibEntryMessage has one FibEntry.
     * </pre>
     */
    FibEntryMessage.FibEntryOrBuilder getFibEntryOrBuilder();
  }
  /**
   * Protobuf type {@code net.named_data.jndn.tests.FibEntryMessage}
   *
   * <pre>
   * Protobuf has no "outer" message type, so we need to put the TLV FibEntry
   * message inside an outer "typeless" FibEntryMessage.
   * </pre>
   */
  public static final class FibEntryMessage extends
      com.google.protobuf.GeneratedMessage
      implements FibEntryMessageOrBuilder {
    // Use FibEntryMessage.newBuilder() to construct.
    private FibEntryMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FibEntryMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FibEntryMessage defaultInstance;
    public static FibEntryMessage getDefaultInstance() {
      return defaultInstance;
    }

    public FibEntryMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FibEntryMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 1026: {
              FibEntry.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = fibEntry_.toBuilder();
              }
              fibEntry_ = input.readMessage(FibEntry.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fibEntry_);
                fibEntry_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FibEntryMessage.class, Builder.class);
    }

    public static com.google.protobuf.Parser<FibEntryMessage> PARSER =
        new com.google.protobuf.AbstractParser<FibEntryMessage>() {
      public FibEntryMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FibEntryMessage(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<FibEntryMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code net.named_data.jndn.tests.FibEntryMessage.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0, 0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1, 1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2, 2),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() { return value; }

      public static PhoneType valueOf(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return FibEntryMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private PhoneType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:net.named_data.jndn.tests.FibEntryMessage.PhoneType)
    }

    public interface NameOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // repeated bytes component = 8;
      /**
       * <code>repeated bytes component = 8;</code>
       */
      java.util.List<com.google.protobuf.ByteString> getComponentList();
      /**
       * <code>repeated bytes component = 8;</code>
       */
      int getComponentCount();
      /**
       * <code>repeated bytes component = 8;</code>
       */
      com.google.protobuf.ByteString getComponent(int index);
    }
    /**
     * Protobuf type {@code net.named_data.jndn.tests.FibEntryMessage.Name}
     */
    public static final class Name extends
        com.google.protobuf.GeneratedMessage
        implements NameOrBuilder {
      // Use Name.newBuilder() to construct.
      private Name(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Name(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Name defaultInstance;
      public static Name getDefaultInstance() {
        return defaultInstance;
      }

      public Name getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Name(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 66: {
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  component_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                  mutable_bitField0_ |= 0x00000001;
                }
                component_.add(input.readBytes());
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            component_ = java.util.Collections.unmodifiableList(component_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_Name_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_Name_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Name.class, Builder.class);
      }

      public static com.google.protobuf.Parser<Name> PARSER =
          new com.google.protobuf.AbstractParser<Name>() {
        public Name parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Name(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<Name> getParserForType() {
        return PARSER;
      }

      // repeated bytes component = 8;
      public static final int COMPONENT_FIELD_NUMBER = 8;
      private java.util.List<com.google.protobuf.ByteString> component_;
      /**
       * <code>repeated bytes component = 8;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getComponentList() {
        return component_;
      }
      /**
       * <code>repeated bytes component = 8;</code>
       */
      public int getComponentCount() {
        return component_.size();
      }
      /**
       * <code>repeated bytes component = 8;</code>
       */
      public com.google.protobuf.ByteString getComponent(int index) {
        return component_.get(index);
      }

      private void initFields() {
        component_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < component_.size(); i++) {
          output.writeBytes(8, component_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < component_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(component_.get(i));
          }
          size += dataSize;
          size += 1 * getComponentList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Name parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Name parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Name parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Name parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Name parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Name parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Name parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Name parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Name parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Name parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Name prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code net.named_data.jndn.tests.FibEntryMessage.Name}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements NameOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_Name_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_Name_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Name.class, Builder.class);
        }

        // Construct using net.named_data.jndn.tests.FibEntryProto.FibEntryMessage.Name.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          component_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_Name_descriptor;
        }

        public Name getDefaultInstanceForType() {
          return Name.getDefaultInstance();
        }

        public Name build() {
          Name result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Name buildPartial() {
          Name result = new Name(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            component_ = java.util.Collections.unmodifiableList(component_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.component_ = component_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Name) {
            return mergeFrom((Name)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Name other) {
          if (other == Name.getDefaultInstance()) return this;
          if (!other.component_.isEmpty()) {
            if (component_.isEmpty()) {
              component_ = other.component_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureComponentIsMutable();
              component_.addAll(other.component_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Name parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Name) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // repeated bytes component = 8;
        private java.util.List<com.google.protobuf.ByteString> component_ = java.util.Collections.emptyList();
        private void ensureComponentIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            component_ = new java.util.ArrayList<com.google.protobuf.ByteString>(component_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated bytes component = 8;</code>
         */
        public java.util.List<com.google.protobuf.ByteString>
            getComponentList() {
          return java.util.Collections.unmodifiableList(component_);
        }
        /**
         * <code>repeated bytes component = 8;</code>
         */
        public int getComponentCount() {
          return component_.size();
        }
        /**
         * <code>repeated bytes component = 8;</code>
         */
        public com.google.protobuf.ByteString getComponent(int index) {
          return component_.get(index);
        }
        /**
         * <code>repeated bytes component = 8;</code>
         */
        public Builder setComponent(
            int index, com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureComponentIsMutable();
          component_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated bytes component = 8;</code>
         */
        public Builder addComponent(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureComponentIsMutable();
          component_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated bytes component = 8;</code>
         */
        public Builder addAllComponent(
            Iterable<? extends com.google.protobuf.ByteString> values) {
          ensureComponentIsMutable();
          super.addAll(values, component_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated bytes component = 8;</code>
         */
        public Builder clearComponent() {
          component_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:net.named_data.jndn.tests.FibEntryMessage.Name)
      }

      static {
        defaultInstance = new Name(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:net.named_data.jndn.tests.FibEntryMessage.Name)
    }

    public interface NextHopRecordOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required uint32 face_id = 105;
      /**
       * <code>required uint32 face_id = 105;</code>
       */
      boolean hasFaceId();
      /**
       * <code>required uint32 face_id = 105;</code>
       */
      int getFaceId();

      // required uint32 cost = 106;
      /**
       * <code>required uint32 cost = 106;</code>
       */
      boolean hasCost();
      /**
       * <code>required uint32 cost = 106;</code>
       */
      int getCost();
    }
    /**
     * Protobuf type {@code net.named_data.jndn.tests.FibEntryMessage.NextHopRecord}
     */
    public static final class NextHopRecord extends
        com.google.protobuf.GeneratedMessage
        implements NextHopRecordOrBuilder {
      // Use NextHopRecord.newBuilder() to construct.
      private NextHopRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private NextHopRecord(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final NextHopRecord defaultInstance;
      public static NextHopRecord getDefaultInstance() {
        return defaultInstance;
      }

      public NextHopRecord getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private NextHopRecord(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 840: {
                bitField0_ |= 0x00000001;
                faceId_ = input.readUInt32();
                break;
              }
              case 848: {
                bitField0_ |= 0x00000002;
                cost_ = input.readUInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_NextHopRecord_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_NextHopRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NextHopRecord.class, Builder.class);
      }

      public static com.google.protobuf.Parser<NextHopRecord> PARSER =
          new com.google.protobuf.AbstractParser<NextHopRecord>() {
        public NextHopRecord parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new NextHopRecord(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<NextHopRecord> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required uint32 face_id = 105;
      public static final int FACE_ID_FIELD_NUMBER = 105;
      private int faceId_;
      /**
       * <code>required uint32 face_id = 105;</code>
       */
      public boolean hasFaceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 face_id = 105;</code>
       */
      public int getFaceId() {
        return faceId_;
      }

      // required uint32 cost = 106;
      public static final int COST_FIELD_NUMBER = 106;
      private int cost_;
      /**
       * <code>required uint32 cost = 106;</code>
       */
      public boolean hasCost() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 cost = 106;</code>
       */
      public int getCost() {
        return cost_;
      }

      private void initFields() {
        faceId_ = 0;
        cost_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasFaceId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasCost()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(105, faceId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeUInt32(106, cost_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(105, faceId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(106, cost_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static NextHopRecord parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static NextHopRecord parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static NextHopRecord parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static NextHopRecord parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static NextHopRecord parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static NextHopRecord parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static NextHopRecord parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static NextHopRecord parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static NextHopRecord parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static NextHopRecord parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(NextHopRecord prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code net.named_data.jndn.tests.FibEntryMessage.NextHopRecord}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements NextHopRecordOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_NextHopRecord_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_NextHopRecord_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  NextHopRecord.class, Builder.class);
        }

        // Construct using net.named_data.jndn.tests.FibEntryProto.FibEntryMessage.NextHopRecord.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          faceId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          cost_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_NextHopRecord_descriptor;
        }

        public NextHopRecord getDefaultInstanceForType() {
          return NextHopRecord.getDefaultInstance();
        }

        public NextHopRecord build() {
          NextHopRecord result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public NextHopRecord buildPartial() {
          NextHopRecord result = new NextHopRecord(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.faceId_ = faceId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.cost_ = cost_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof NextHopRecord) {
            return mergeFrom((NextHopRecord)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(NextHopRecord other) {
          if (other == NextHopRecord.getDefaultInstance()) return this;
          if (other.hasFaceId()) {
            setFaceId(other.getFaceId());
          }
          if (other.hasCost()) {
            setCost(other.getCost());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasFaceId()) {
            
            return false;
          }
          if (!hasCost()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          NextHopRecord parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (NextHopRecord) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required uint32 face_id = 105;
        private int faceId_ ;
        /**
         * <code>required uint32 face_id = 105;</code>
         */
        public boolean hasFaceId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required uint32 face_id = 105;</code>
         */
        public int getFaceId() {
          return faceId_;
        }
        /**
         * <code>required uint32 face_id = 105;</code>
         */
        public Builder setFaceId(int value) {
          bitField0_ |= 0x00000001;
          faceId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 face_id = 105;</code>
         */
        public Builder clearFaceId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          faceId_ = 0;
          onChanged();
          return this;
        }

        // required uint32 cost = 106;
        private int cost_ ;
        /**
         * <code>required uint32 cost = 106;</code>
         */
        public boolean hasCost() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required uint32 cost = 106;</code>
         */
        public int getCost() {
          return cost_;
        }
        /**
         * <code>required uint32 cost = 106;</code>
         */
        public Builder setCost(int value) {
          bitField0_ |= 0x00000002;
          cost_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 cost = 106;</code>
         */
        public Builder clearCost() {
          bitField0_ = (bitField0_ & ~0x00000002);
          cost_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:net.named_data.jndn.tests.FibEntryMessage.NextHopRecord)
      }

      static {
        defaultInstance = new NextHopRecord(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:net.named_data.jndn.tests.FibEntryMessage.NextHopRecord)
    }

    public interface FibEntryOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required .net.named_data.jndn.tests.FibEntryMessage.PhoneType phone = 69;
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.PhoneType phone = 69;</code>
       */
      boolean hasPhone();
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.PhoneType phone = 69;</code>
       */
      PhoneType getPhone();

      // required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
       */
      boolean hasName();
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
       */
      Name getName();
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
       */
      NameOrBuilder getNameOrBuilder();

      // repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;
      /**
       * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
       */
      java.util.List<NextHopRecord>
          getNextHopRecordsList();
      /**
       * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
       */
      NextHopRecord getNextHopRecords(int index);
      /**
       * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
       */
      int getNextHopRecordsCount();
      /**
       * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
       */
      java.util.List<? extends NextHopRecordOrBuilder>
          getNextHopRecordsOrBuilderList();
      /**
       * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
       */
      NextHopRecordOrBuilder getNextHopRecordsOrBuilder(
              int index);
    }
    /**
     * Protobuf type {@code net.named_data.jndn.tests.FibEntryMessage.FibEntry}
     */
    public static final class FibEntry extends
        com.google.protobuf.GeneratedMessage
        implements FibEntryOrBuilder {
      // Use FibEntry.newBuilder() to construct.
      private FibEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private FibEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final FibEntry defaultInstance;
      public static FibEntry getDefaultInstance() {
        return defaultInstance;
      }

      public FibEntry getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private FibEntry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 58: {
                Name.Builder subBuilder = null;
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                  subBuilder = name_.toBuilder();
                }
                name_ = input.readMessage(Name.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(name_);
                  name_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000002;
                break;
              }
              case 552: {
                int rawValue = input.readEnum();
                PhoneType value = PhoneType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(69, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  phone_ = value;
                }
                break;
              }
              case 1034: {
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  nextHopRecords_ = new java.util.ArrayList<NextHopRecord>();
                  mutable_bitField0_ |= 0x00000004;
                }
                nextHopRecords_.add(input.readMessage(NextHopRecord.PARSER, extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
            nextHopRecords_ = java.util.Collections.unmodifiableList(nextHopRecords_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_FibEntry_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_FibEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FibEntry.class, Builder.class);
      }

      public static com.google.protobuf.Parser<FibEntry> PARSER =
          new com.google.protobuf.AbstractParser<FibEntry>() {
        public FibEntry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new FibEntry(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<FibEntry> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required .net.named_data.jndn.tests.FibEntryMessage.PhoneType phone = 69;
      public static final int PHONE_FIELD_NUMBER = 69;
      private PhoneType phone_;
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.PhoneType phone = 69;</code>
       */
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.PhoneType phone = 69;</code>
       */
      public PhoneType getPhone() {
        return phone_;
      }

      // required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;
      public static final int NAME_FIELD_NUMBER = 7;
      private Name name_;
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
       */
      public Name getName() {
        return name_;
      }
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
       */
      public NameOrBuilder getNameOrBuilder() {
        return name_;
      }

      // repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;
      public static final int NEXT_HOP_RECORDS_FIELD_NUMBER = 129;
      private java.util.List<NextHopRecord> nextHopRecords_;
      /**
       * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
       */
      public java.util.List<NextHopRecord> getNextHopRecordsList() {
        return nextHopRecords_;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
       */
      public java.util.List<? extends NextHopRecordOrBuilder>
          getNextHopRecordsOrBuilderList() {
        return nextHopRecords_;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
       */
      public int getNextHopRecordsCount() {
        return nextHopRecords_.size();
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
       */
      public NextHopRecord getNextHopRecords(int index) {
        return nextHopRecords_.get(index);
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
       */
      public NextHopRecordOrBuilder getNextHopRecordsOrBuilder(
          int index) {
        return nextHopRecords_.get(index);
      }

      private void initFields() {
        phone_ = PhoneType.MOBILE;
        name_ = Name.getDefaultInstance();
        nextHopRecords_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasPhone()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        for (int i = 0; i < getNextHopRecordsCount(); i++) {
          if (!getNextHopRecords(i).isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeMessage(7, name_);
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(69, phone_.getNumber());
        }
        for (int i = 0; i < nextHopRecords_.size(); i++) {
          output.writeMessage(129, nextHopRecords_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, name_);
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(69, phone_.getNumber());
        }
        for (int i = 0; i < nextHopRecords_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(129, nextHopRecords_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static FibEntry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static FibEntry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static FibEntry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static FibEntry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static FibEntry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static FibEntry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static FibEntry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static FibEntry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static FibEntry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static FibEntry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(FibEntry prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code net.named_data.jndn.tests.FibEntryMessage.FibEntry}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements FibEntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_FibEntry_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_FibEntry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  FibEntry.class, Builder.class);
        }

        // Construct using net.named_data.jndn.tests.FibEntryProto.FibEntryMessage.FibEntry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getNameFieldBuilder();
            getNextHopRecordsFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          phone_ = PhoneType.MOBILE;
          bitField0_ = (bitField0_ & ~0x00000001);
          if (nameBuilder_ == null) {
            name_ = Name.getDefaultInstance();
          } else {
            nameBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          if (nextHopRecordsBuilder_ == null) {
            nextHopRecords_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            nextHopRecordsBuilder_.clear();
          }
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_FibEntry_descriptor;
        }

        public FibEntry getDefaultInstanceForType() {
          return FibEntry.getDefaultInstance();
        }

        public FibEntry build() {
          FibEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public FibEntry buildPartial() {
          FibEntry result = new FibEntry(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.phone_ = phone_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          if (nameBuilder_ == null) {
            result.name_ = name_;
          } else {
            result.name_ = nameBuilder_.build();
          }
          if (nextHopRecordsBuilder_ == null) {
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
              nextHopRecords_ = java.util.Collections.unmodifiableList(nextHopRecords_);
              bitField0_ = (bitField0_ & ~0x00000004);
            }
            result.nextHopRecords_ = nextHopRecords_;
          } else {
            result.nextHopRecords_ = nextHopRecordsBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof FibEntry) {
            return mergeFrom((FibEntry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(FibEntry other) {
          if (other == FibEntry.getDefaultInstance()) return this;
          if (other.hasPhone()) {
            setPhone(other.getPhone());
          }
          if (other.hasName()) {
            mergeName(other.getName());
          }
          if (nextHopRecordsBuilder_ == null) {
            if (!other.nextHopRecords_.isEmpty()) {
              if (nextHopRecords_.isEmpty()) {
                nextHopRecords_ = other.nextHopRecords_;
                bitField0_ = (bitField0_ & ~0x00000004);
              } else {
                ensureNextHopRecordsIsMutable();
                nextHopRecords_.addAll(other.nextHopRecords_);
              }
              onChanged();
            }
          } else {
            if (!other.nextHopRecords_.isEmpty()) {
              if (nextHopRecordsBuilder_.isEmpty()) {
                nextHopRecordsBuilder_.dispose();
                nextHopRecordsBuilder_ = null;
                nextHopRecords_ = other.nextHopRecords_;
                bitField0_ = (bitField0_ & ~0x00000004);
                nextHopRecordsBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getNextHopRecordsFieldBuilder() : null;
              } else {
                nextHopRecordsBuilder_.addAllMessages(other.nextHopRecords_);
              }
            }
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasPhone()) {
            
            return false;
          }
          if (!hasName()) {
            
            return false;
          }
          for (int i = 0; i < getNextHopRecordsCount(); i++) {
            if (!getNextHopRecords(i).isInitialized()) {
              
              return false;
            }
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          FibEntry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (FibEntry) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required .net.named_data.jndn.tests.FibEntryMessage.PhoneType phone = 69;
        private PhoneType phone_ = PhoneType.MOBILE;
        /**
         * <code>required .net.named_data.jndn.tests.FibEntryMessage.PhoneType phone = 69;</code>
         */
        public boolean hasPhone() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .net.named_data.jndn.tests.FibEntryMessage.PhoneType phone = 69;</code>
         */
        public PhoneType getPhone() {
          return phone_;
        }
        /**
         * <code>required .net.named_data.jndn.tests.FibEntryMessage.PhoneType phone = 69;</code>
         */
        public Builder setPhone(PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          phone_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .net.named_data.jndn.tests.FibEntryMessage.PhoneType phone = 69;</code>
         */
        public Builder clearPhone() {
          bitField0_ = (bitField0_ & ~0x00000001);
          phone_ = PhoneType.MOBILE;
          onChanged();
          return this;
        }

        // required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;
        private Name name_ = Name.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            Name, Name.Builder, NameOrBuilder> nameBuilder_;
        /**
         * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
         */
        public Name getName() {
          if (nameBuilder_ == null) {
            return name_;
          } else {
            return nameBuilder_.getMessage();
          }
        }
        /**
         * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
         */
        public Builder setName(Name value) {
          if (nameBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            name_ = value;
            onChanged();
          } else {
            nameBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
         */
        public Builder setName(
            Name.Builder builderForValue) {
          if (nameBuilder_ == null) {
            name_ = builderForValue.build();
            onChanged();
          } else {
            nameBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
         */
        public Builder mergeName(Name value) {
          if (nameBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002) &&
                name_ != Name.getDefaultInstance()) {
              name_ =
                Name.newBuilder(name_).mergeFrom(value).buildPartial();
            } else {
              name_ = value;
            }
            onChanged();
          } else {
            nameBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
         */
        public Builder clearName() {
          if (nameBuilder_ == null) {
            name_ = Name.getDefaultInstance();
            onChanged();
          } else {
            nameBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        /**
         * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
         */
        public Name.Builder getNameBuilder() {
          bitField0_ |= 0x00000002;
          onChanged();
          return getNameFieldBuilder().getBuilder();
        }
        /**
         * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
         */
        public NameOrBuilder getNameOrBuilder() {
          if (nameBuilder_ != null) {
            return nameBuilder_.getMessageOrBuilder();
          } else {
            return name_;
          }
        }
        /**
         * <code>required .net.named_data.jndn.tests.FibEntryMessage.Name name = 7;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            Name, Name.Builder, NameOrBuilder>
            getNameFieldBuilder() {
          if (nameBuilder_ == null) {
            nameBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                Name, Name.Builder, NameOrBuilder>(
                    name_,
                    getParentForChildren(),
                    isClean());
            name_ = null;
          }
          return nameBuilder_;
        }

        // repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;
        private java.util.List<NextHopRecord> nextHopRecords_ =
          java.util.Collections.emptyList();
        private void ensureNextHopRecordsIsMutable() {
          if (!((bitField0_ & 0x00000004) == 0x00000004)) {
            nextHopRecords_ = new java.util.ArrayList<NextHopRecord>(nextHopRecords_);
            bitField0_ |= 0x00000004;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilder<
            NextHopRecord, NextHopRecord.Builder, NextHopRecordOrBuilder> nextHopRecordsBuilder_;

        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public java.util.List<NextHopRecord> getNextHopRecordsList() {
          if (nextHopRecordsBuilder_ == null) {
            return java.util.Collections.unmodifiableList(nextHopRecords_);
          } else {
            return nextHopRecordsBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public int getNextHopRecordsCount() {
          if (nextHopRecordsBuilder_ == null) {
            return nextHopRecords_.size();
          } else {
            return nextHopRecordsBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public NextHopRecord getNextHopRecords(int index) {
          if (nextHopRecordsBuilder_ == null) {
            return nextHopRecords_.get(index);
          } else {
            return nextHopRecordsBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public Builder setNextHopRecords(
            int index, NextHopRecord value) {
          if (nextHopRecordsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureNextHopRecordsIsMutable();
            nextHopRecords_.set(index, value);
            onChanged();
          } else {
            nextHopRecordsBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public Builder setNextHopRecords(
            int index, NextHopRecord.Builder builderForValue) {
          if (nextHopRecordsBuilder_ == null) {
            ensureNextHopRecordsIsMutable();
            nextHopRecords_.set(index, builderForValue.build());
            onChanged();
          } else {
            nextHopRecordsBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public Builder addNextHopRecords(NextHopRecord value) {
          if (nextHopRecordsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureNextHopRecordsIsMutable();
            nextHopRecords_.add(value);
            onChanged();
          } else {
            nextHopRecordsBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public Builder addNextHopRecords(
            int index, NextHopRecord value) {
          if (nextHopRecordsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureNextHopRecordsIsMutable();
            nextHopRecords_.add(index, value);
            onChanged();
          } else {
            nextHopRecordsBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public Builder addNextHopRecords(
            NextHopRecord.Builder builderForValue) {
          if (nextHopRecordsBuilder_ == null) {
            ensureNextHopRecordsIsMutable();
            nextHopRecords_.add(builderForValue.build());
            onChanged();
          } else {
            nextHopRecordsBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public Builder addNextHopRecords(
            int index, NextHopRecord.Builder builderForValue) {
          if (nextHopRecordsBuilder_ == null) {
            ensureNextHopRecordsIsMutable();
            nextHopRecords_.add(index, builderForValue.build());
            onChanged();
          } else {
            nextHopRecordsBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public Builder addAllNextHopRecords(
            Iterable<? extends NextHopRecord> values) {
          if (nextHopRecordsBuilder_ == null) {
            ensureNextHopRecordsIsMutable();
            super.addAll(values, nextHopRecords_);
            onChanged();
          } else {
            nextHopRecordsBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public Builder clearNextHopRecords() {
          if (nextHopRecordsBuilder_ == null) {
            nextHopRecords_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000004);
            onChanged();
          } else {
            nextHopRecordsBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public Builder removeNextHopRecords(int index) {
          if (nextHopRecordsBuilder_ == null) {
            ensureNextHopRecordsIsMutable();
            nextHopRecords_.remove(index);
            onChanged();
          } else {
            nextHopRecordsBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public NextHopRecord.Builder getNextHopRecordsBuilder(
            int index) {
          return getNextHopRecordsFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public NextHopRecordOrBuilder getNextHopRecordsOrBuilder(
            int index) {
          if (nextHopRecordsBuilder_ == null) {
            return nextHopRecords_.get(index);  } else {
            return nextHopRecordsBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public java.util.List<? extends NextHopRecordOrBuilder>
             getNextHopRecordsOrBuilderList() {
          if (nextHopRecordsBuilder_ != null) {
            return nextHopRecordsBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(nextHopRecords_);
          }
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public NextHopRecord.Builder addNextHopRecordsBuilder() {
          return getNextHopRecordsFieldBuilder().addBuilder(
              NextHopRecord.getDefaultInstance());
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public NextHopRecord.Builder addNextHopRecordsBuilder(
            int index) {
          return getNextHopRecordsFieldBuilder().addBuilder(
              index, NextHopRecord.getDefaultInstance());
        }
        /**
         * <code>repeated .net.named_data.jndn.tests.FibEntryMessage.NextHopRecord next_hop_records = 129;</code>
         */
        public java.util.List<NextHopRecord.Builder>
             getNextHopRecordsBuilderList() {
          return getNextHopRecordsFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            NextHopRecord, NextHopRecord.Builder, NextHopRecordOrBuilder>
            getNextHopRecordsFieldBuilder() {
          if (nextHopRecordsBuilder_ == null) {
            nextHopRecordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                NextHopRecord, NextHopRecord.Builder, NextHopRecordOrBuilder>(
                    nextHopRecords_,
                    ((bitField0_ & 0x00000004) == 0x00000004),
                    getParentForChildren(),
                    isClean());
            nextHopRecords_ = null;
          }
          return nextHopRecordsBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:net.named_data.jndn.tests.FibEntryMessage.FibEntry)
      }

      static {
        defaultInstance = new FibEntry(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:net.named_data.jndn.tests.FibEntryMessage.FibEntry)
    }

    private int bitField0_;
    // required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;
    public static final int FIB_ENTRY_FIELD_NUMBER = 128;
    private FibEntry fibEntry_;
    /**
     * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
     *
     * <pre>
     * A FibEntryMessage has one FibEntry.
     * </pre>
     */
    public boolean hasFibEntry() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
     *
     * <pre>
     * A FibEntryMessage has one FibEntry.
     * </pre>
     */
    public FibEntry getFibEntry() {
      return fibEntry_;
    }
    /**
     * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
     *
     * <pre>
     * A FibEntryMessage has one FibEntry.
     * </pre>
     */
    public FibEntryOrBuilder getFibEntryOrBuilder() {
      return fibEntry_;
    }

    private void initFields() {
      fibEntry_ = FibEntry.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFibEntry()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getFibEntry().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(128, fibEntry_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(128, fibEntry_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static FibEntryMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FibEntryMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FibEntryMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FibEntryMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FibEntryMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static FibEntryMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static FibEntryMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static FibEntryMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static FibEntryMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static FibEntryMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(FibEntryMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.named_data.jndn.tests.FibEntryMessage}
     *
     * <pre>
     * Protobuf has no "outer" message type, so we need to put the TLV FibEntry
     * message inside an outer "typeless" FibEntryMessage.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements FibEntryMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FibEntryMessage.class, Builder.class);
      }

      // Construct using net.named_data.jndn.tests.FibEntryProto.FibEntryMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFibEntryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (fibEntryBuilder_ == null) {
          fibEntry_ = FibEntry.getDefaultInstance();
        } else {
          fibEntryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FibEntryProto.internal_static_net_named_data_jndn_tests_FibEntryMessage_descriptor;
      }

      public FibEntryMessage getDefaultInstanceForType() {
        return FibEntryMessage.getDefaultInstance();
      }

      public FibEntryMessage build() {
        FibEntryMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public FibEntryMessage buildPartial() {
        FibEntryMessage result = new FibEntryMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (fibEntryBuilder_ == null) {
          result.fibEntry_ = fibEntry_;
        } else {
          result.fibEntry_ = fibEntryBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FibEntryMessage) {
          return mergeFrom((FibEntryMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FibEntryMessage other) {
        if (other == FibEntryMessage.getDefaultInstance()) return this;
        if (other.hasFibEntry()) {
          mergeFibEntry(other.getFibEntry());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFibEntry()) {
          
          return false;
        }
        if (!getFibEntry().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FibEntryMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FibEntryMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;
      private FibEntry fibEntry_ = FibEntry.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          FibEntry, FibEntry.Builder, FibEntryOrBuilder> fibEntryBuilder_;
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
       *
       * <pre>
       * A FibEntryMessage has one FibEntry.
       * </pre>
       */
      public boolean hasFibEntry() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
       *
       * <pre>
       * A FibEntryMessage has one FibEntry.
       * </pre>
       */
      public FibEntry getFibEntry() {
        if (fibEntryBuilder_ == null) {
          return fibEntry_;
        } else {
          return fibEntryBuilder_.getMessage();
        }
      }
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
       *
       * <pre>
       * A FibEntryMessage has one FibEntry.
       * </pre>
       */
      public Builder setFibEntry(FibEntry value) {
        if (fibEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fibEntry_ = value;
          onChanged();
        } else {
          fibEntryBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
       *
       * <pre>
       * A FibEntryMessage has one FibEntry.
       * </pre>
       */
      public Builder setFibEntry(
          FibEntry.Builder builderForValue) {
        if (fibEntryBuilder_ == null) {
          fibEntry_ = builderForValue.build();
          onChanged();
        } else {
          fibEntryBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
       *
       * <pre>
       * A FibEntryMessage has one FibEntry.
       * </pre>
       */
      public Builder mergeFibEntry(FibEntry value) {
        if (fibEntryBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              fibEntry_ != FibEntry.getDefaultInstance()) {
            fibEntry_ =
              FibEntry.newBuilder(fibEntry_).mergeFrom(value).buildPartial();
          } else {
            fibEntry_ = value;
          }
          onChanged();
        } else {
          fibEntryBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
       *
       * <pre>
       * A FibEntryMessage has one FibEntry.
       * </pre>
       */
      public Builder clearFibEntry() {
        if (fibEntryBuilder_ == null) {
          fibEntry_ = FibEntry.getDefaultInstance();
          onChanged();
        } else {
          fibEntryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
       *
       * <pre>
       * A FibEntryMessage has one FibEntry.
       * </pre>
       */
      public FibEntry.Builder getFibEntryBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getFibEntryFieldBuilder().getBuilder();
      }
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
       *
       * <pre>
       * A FibEntryMessage has one FibEntry.
       * </pre>
       */
      public FibEntryOrBuilder getFibEntryOrBuilder() {
        if (fibEntryBuilder_ != null) {
          return fibEntryBuilder_.getMessageOrBuilder();
        } else {
          return fibEntry_;
        }
      }
      /**
       * <code>required .net.named_data.jndn.tests.FibEntryMessage.FibEntry fib_entry = 128;</code>
       *
       * <pre>
       * A FibEntryMessage has one FibEntry.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          FibEntry, FibEntry.Builder, FibEntryOrBuilder>
          getFibEntryFieldBuilder() {
        if (fibEntryBuilder_ == null) {
          fibEntryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              FibEntry, FibEntry.Builder, FibEntryOrBuilder>(
                  fibEntry_,
                  getParentForChildren(),
                  isClean());
          fibEntry_ = null;
        }
        return fibEntryBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:net.named_data.jndn.tests.FibEntryMessage)
    }

    static {
      defaultInstance = new FibEntryMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.named_data.jndn.tests.FibEntryMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_named_data_jndn_tests_FibEntryMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_named_data_jndn_tests_FibEntryMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_named_data_jndn_tests_FibEntryMessage_Name_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_named_data_jndn_tests_FibEntryMessage_Name_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_named_data_jndn_tests_FibEntryMessage_NextHopRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_named_data_jndn_tests_FibEntryMessage_NextHopRecord_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_named_data_jndn_tests_FibEntryMessage_FibEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_named_data_jndn_tests_FibEntryMessage_FibEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025fib-entry-proto.proto\022\031net.named_data." +
      "jndn.tests\"\270\003\n\017FibEntryMessage\022G\n\tfib_en" +
      "try\030\200\001 \002(\01323.net.named_data.jndn.tests.F" +
      "ibEntryMessage.FibEntry\032\031\n\004Name\022\021\n\tcompo" +
      "nent\030\010 \003(\014\032.\n\rNextHopRecord\022\017\n\007face_id\030i" +
      " \002(\r\022\014\n\004cost\030j \002(\r\032\343\001\n\010FibEntry\022C\n\005phone" +
      "\030E \002(\01624.net.named_data.jndn.tests.FibEn" +
      "tryMessage.PhoneType\022=\n\004name\030\007 \002(\0132/.net" +
      ".named_data.jndn.tests.FibEntryMessage.N" +
      "ame\022S\n\020next_hop_records\030\201\001 \003(\01328.net.nam",
      "ed_data.jndn.tests.FibEntryMessage.NextH" +
      "opRecord\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOM" +
      "E\020\001\022\010\n\004WORK\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_named_data_jndn_tests_FibEntryMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_named_data_jndn_tests_FibEntryMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_named_data_jndn_tests_FibEntryMessage_descriptor,
              new String[] { "FibEntry", });
          internal_static_net_named_data_jndn_tests_FibEntryMessage_Name_descriptor =
            internal_static_net_named_data_jndn_tests_FibEntryMessage_descriptor.getNestedTypes().get(0);
          internal_static_net_named_data_jndn_tests_FibEntryMessage_Name_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_named_data_jndn_tests_FibEntryMessage_Name_descriptor,
              new String[] { "Component", });
          internal_static_net_named_data_jndn_tests_FibEntryMessage_NextHopRecord_descriptor =
            internal_static_net_named_data_jndn_tests_FibEntryMessage_descriptor.getNestedTypes().get(1);
          internal_static_net_named_data_jndn_tests_FibEntryMessage_NextHopRecord_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_named_data_jndn_tests_FibEntryMessage_NextHopRecord_descriptor,
              new String[] { "FaceId", "Cost", });
          internal_static_net_named_data_jndn_tests_FibEntryMessage_FibEntry_descriptor =
            internal_static_net_named_data_jndn_tests_FibEntryMessage_descriptor.getNestedTypes().get(2);
          internal_static_net_named_data_jndn_tests_FibEntryMessage_FibEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_named_data_jndn_tests_FibEntryMessage_FibEntry_descriptor,
              new String[] { "Phone", "Name", "NextHopRecords", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
